export const adminScreenshots = [
  {
    title: 'Login',
    description: 'Admin membuka halaman login dan masuk menggunakan akun yang sudah disiapkan.',
    image: '/screenshots/admin/login.png',
    width: 1920,
    height: 955,
  },
  {
    title: 'Dashboard utama',
    description: 'Setelah berhasil masuk, admin melihat ringkasan data sistem dan pintasan pengelolaan.',
    image: '/screenshots/admin/dashboard-utama.png',
    width: 1920,
    height: 954,
  },
  {
    title: 'Buka kode kelas',
    description: 'Admin membuka menu Kode Kelas untuk melihat daftar kelas yang sudah tersedia.',
    image: '/screenshots/admin/kode-kelas.png',
    width: 1920,
    height: 954,
  },
  {
    title: 'Tambah kode kelas',
    description: 'Admin mengisi kode kelas baru agar siswa dan jadwal bisa dikelompokkan dengan benar.',
    image: '/screenshots/admin/tambah-kode-kelas.png',
    width: 717,
    height: 446,
  },
  {
    title: 'Buka tahun ajaran',
    description: 'Admin membuka menu Tahun Ajaran untuk memastikan periode pembelajaran aktif sudah sesuai.',
    image: '/screenshots/admin/tahun-ajaran.png',
    width: 1920,
    height: 953,
  },
  {
    title: 'Tambah tahun ajaran',
    description: 'Admin menambahkan tahun ajaran baru jika periode uji coba belum tersedia di sistem.',
    image: '/screenshots/admin/tambah-tahun-ajaran.png',
    width: 741,
    height: 492,
  },
  {
    title: 'Buka data pengguna',
    description: 'Admin membuka menu Semua Pengguna untuk mengelola akun guru, siswa, dan admin.',
    image: '/screenshots/admin/user.png',
    width: 1920,
    height: 954,
  },
  {
    title: 'Tambah user',
    description: 'Admin menambahkan akun guru atau siswa, lalu memilih role yang sesuai.',
    image: '/screenshots/admin/tambah-user.png',
    width: 587,
    height: 704,
  },
  {
    title: 'Buka mata pelajaran',
    description: 'Admin membuka menu Mata Pelajaran untuk melihat daftar mapel yang sudah terdaftar.',
    image: '/screenshots/admin/mata-pelajaran.png',
    width: 1920,
    height: 954,
  },
  {
    title: 'Tambah mata pelajaran',
    description: 'Admin menambahkan mata pelajaran yang akan digunakan guru saat membuat materi, tugas, dan ujian.',
    image: '/screenshots/admin/tambah-mata-pelajaran.png',
    width: 648,
    height: 432,
  },
];
