export const guruScreenshots = [
  {
    title: 'Login',
    description: 'Guru membuka halaman login dan masuk menggunakan akun guru yang sudah dibuat oleh admin.',
    image: '/screenshots/guru/login.png',
    width: 1920,
    height: 953,
  },
  {
    title: 'Dashboard utama',
    description: 'Guru melihat ringkasan aktivitas mengajar, jadwal, tugas, ujian, dan pintasan fitur utama.',
    image: '/screenshots/guru/dashboard-utama.png',
    width: 1920,
    height: 956,
  },
  {
    title: 'Materi pelajaran',
    description: 'Guru membuka menu Materi Pelajaran untuk melihat daftar materi yang sudah dibuat.',
    image: '/screenshots/guru/materi-pelajaran.png',
    width: 1920,
    height: 951,
  },
  {
    title: 'Tambah materi pelajaran',
    description: 'Guru mengisi judul, mata pelajaran, kelas, deskripsi, dan lampiran materi sebelum disimpan.',
    image: '/screenshots/guru/tambah-materi-pelajaran.png',
    width: 606,
    height: 715,
  },
  {
    title: 'Penugasan',
    description: 'Guru membuka menu Penugasan untuk memantau tugas yang aktif dan tugas yang sudah dibuat.',
    image: '/screenshots/guru/penugasan.png',
    width: 1920,
    height: 948,
  },
  {
    title: 'Tambah tugas',
    description: 'Guru membuat tugas baru dengan memilih mata pelajaran, kelas tujuan, instruksi, dan deadline.',
    image: '/screenshots/guru/tambah-tugas.png',
    width: 636,
    height: 748,
  },
  {
    title: 'Monitoring evaluasi penugasan',
    description: 'Guru mengecek pengumpulan tugas siswa, lalu memberi nilai atau catatan evaluasi.',
    image: '/screenshots/guru/monitor-evaluasi-penugasan.png',
    width: 1920,
    height: 954,
  },
  {
    title: 'Ujian - bank soal',
    description: 'Guru membuka menu Ujian untuk melihat bank soal dan daftar ujian yang tersedia.',
    image: '/screenshots/guru/ujian-bank-soal.png',
    width: 1920,
    height: 949,
  },
  {
    title: 'Pembuatan ujian tahap 1',
    description: 'Guru mengisi informasi dasar ujian, integrasi mata pelajaran, kelas, kategori, dan jadwal ujian.',
    image: '/screenshots/guru/pembuatan-ujian-1.png',
    width: 1920,
    height: 951,
  },
  {
    title: 'Pembuatan ujian tahap 2',
    description: 'Guru menyusun soal ujian, pilihan jawaban, kunci jawaban, dan pengaturan soal.',
    image: '/screenshots/guru/pembuatan-ujian-2.png',
    width: 1920,
    height: 948,
  },
  {
    title: 'Pembuatan ujian tahap 3 dan publish',
    description: 'Guru meninjau ringkasan ujian, memastikan data sudah benar, lalu mempublikasikan ujian.',
    image: '/screenshots/guru/pembuatan-ujian-3.png',
    width: 1920,
    height: 950,
  },
  {
    title: 'Monitoring ujian',
    description: 'Guru memantau pengerjaan ujian siswa, termasuk status pengerjaan dan catatan aktivitas saat ujian.',
    image: '/screenshots/guru/monitoring-ujian.png',
    width: 1920,
    height: 953,
  },
];
