export const studentScreenshots = [
  {
    title: 'Login',
    description: 'Siswa membuka halaman login dan masuk menggunakan akun siswa yang sudah dibuat oleh admin.',
    image: '/screenshots/siswa/login.png',
    width: 1920,
    height: 952,
  },
  {
    title: 'Dashboard utama',
    description: 'Setelah berhasil masuk, siswa melihat ringkasan kelas, tugas, materi, ujian, dan aktivitas terbaru.',
    image: '/screenshots/siswa/dashboard-utama.png',
    width: 1920,
    height: 952,
  },
  {
    title: 'Tugas',
    description: 'Siswa membuka menu Tugas untuk melihat daftar tugas yang diberikan guru beserta status pengumpulan.',
    image: '/screenshots/siswa/tugas.png',
    width: 1920,
    height: 947,
  },
  {
    title: 'Upload dan kirim tugas',
    description: 'Siswa mengunggah file jawaban atau melengkapi jawaban sesuai instruksi, lalu mengirim tugas.',
    image: '/screenshots/siswa/upload-kirim-tugas.png',
    width: 624,
    height: 525,
  },
  {
    title: 'Materi',
    description: 'Siswa membuka menu Materi untuk melihat materi pembelajaran yang sudah dibagikan oleh guru.',
    image: '/screenshots/siswa/materi.png',
    width: 1920,
    height: 950,
  },
  {
    title: 'Lihat materi',
    description: 'Siswa membuka detail materi untuk membaca isi materi dan melihat lampiran pendukung jika tersedia.',
    image: '/screenshots/siswa/lihat-materi.png',
    width: 1920,
    height: 950,
  },
  {
    title: 'Ujian',
    description: 'Siswa membuka menu Ujian untuk melihat daftar ujian yang tersedia dan siap dikerjakan.',
    image: '/screenshots/siswa/ujian.png',
    width: 1920,
    height: 953,
  },
  {
    title: 'Mulai ujian',
    description: 'Siswa memilih ujian yang tersedia, memeriksa informasi ujian, lalu menekan tombol mulai ujian.',
    image: '/screenshots/siswa/mulai-ujian.png',
    width: 672,
    height: 610,
  },
  {
    title: 'Peringatan ujian',
    description: 'Siswa membaca peringatan ujian, termasuk aturan agar tetap berada pada halaman ujian selama pengerjaan.',
    image: '/screenshots/siswa/peringatan-ujian.png',
    width: 689,
    height: 609,
  },
  {
    title: 'Jawab ujian',
    description: 'Siswa mengerjakan soal pada form ujian, memilih jawaban, lalu mengirim ujian setelah selesai.',
    image: '/screenshots/siswa/jawab-ujian.png',
    width: 1920,
    height: 1080,
  },
  {
    title: 'Cek hasil ujian',
    description: 'Setelah ujian selesai dan hasil dibuka, siswa mengecek nilai ujian pada daftar hasil yang tersedia.',
    image: '/screenshots/siswa/cek-hasil-ujian.png',
    width: 1920,
    height: 957,
  },
  {
    title: 'Detail nilai dan lihat evaluasi',
    description: 'Siswa membuka detail nilai untuk melihat ringkasan hasil, lalu memilih opsi lihat evaluasi.',
    image: '/screenshots/siswa/detail-nilai-dan-lihat-evaluasi.png',
    width: 592,
    height: 747,
  },
  {
    title: 'Hasil evaluasi',
    description: 'Siswa melihat evaluasi jawaban ujian untuk memahami hasil pengerjaan dan pembahasan yang tersedia.',
    image: '/screenshots/siswa/hasil-evaluasi.png',
    width: 1920,
    height: 951,
  },
];
